image: php:7.2-fpm

laravelTesting: &laravelTesting
    step:
        name: Run Laravel Unit Testing
        caches:
            - composer
            - node
        script:
            - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
            - yes | pecl install mcrypt-1.0.1
            - docker-php-ext-install pdo_mysql bcmath exif
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > ~/.composer/auth.json
            - composer install
            - ln -f -s .env.pipelines .env
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - ./vendor/bin/phpunit
            - curl -vk http://localhost:8000
        services:
            - mysql

pipelines:
    branches:
        deploy/staging:
            -   step:
                    name: Deploy to Staging
                    deployment: staging
                    script:
                        -   pipe: atlassian/ssh-run:0.2.2
                            variables:
                                SSH_USER: $SERVER_USERNAME
                                SERVER: $SERVER_IP_ADDRESS
                                MODE: 'script'
                                COMMAND: 'devops/deploys/staging.sh'

definitions:
    services:
        mysql:
            image: mysql:5.7
            environment:
                MYSQL_DATABASE: 'homestead'
                MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
                MYSQL_USER: 'homestead'
                MYSQL_PASSWORD: 'secret'
